services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app:/app
      - ./models:/models
      - ./configs:/configs
      - ./dataset/birdclef-2025/train.csv:/dataset/train.csv:ro
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MODEL_PATH=/models/best_model.pth
      - TRAIN_CSV_PATH=/dataset/train.csv
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data: